# Generated by Django 5.2.15 on 2026-06-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='daily_quota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='jitter_max',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sim',
            name='jitter_min',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='sim',
            name='rate_per_day',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='sim',
            name='rate_per_hour',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='sim',
            name='rate_per_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='sim',
            name='work_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='work_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
