# Generated by Django 5.2.15 on 2026-06-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0002_sim_daily_quota_sim_jitter_max_sim_jitter_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='ownsms.account')),
            ],
        ),
    ]
