# Generated by Django 5.2.15 on 2026-06-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0004_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('rotate_sims', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('queued', models.BooleanField(default=True)),
                ('callback_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='running', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ownsms.account')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ownsms.device')),
                ('sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='ownsms.sim')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ownsms.campaign'),
        ),
    ]
