# Generated by Django 5.2.15 on 2026-06-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0005_message_scheduled_at_campaign_message_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('secret', models.CharField(max_length=64)),
                ('events', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='ownsms.account')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=500)),
                ('payload', models.JSONField()),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='ownsms.account')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ownsms.message')),
            ],
        ),
    ]
