# Generated by Django 5.2.15 on 2026-06-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0006_webhook_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='callback_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
