# Generated by Django 5.2.15 on 2026-06-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0007_apikey_is_test_message_callback_url_message_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='ip_allowlist',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ownsms.account')),
            ],
        ),
    ]
