# Generated by Django 5.2.15 on 2026-07-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0008_apikey_ip_allowlist_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Akkaunt', 'verbose_name_plural': 'Akkauntlar'},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API kalit', 'verbose_name_plural': 'API kalitlar'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit yozuvi', 'verbose_name_plural': 'Audit jurnali'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Rassilka', 'verbose_name_plural': 'Rassilkalar'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Qurilma', 'verbose_name_plural': 'Qurilmalar'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='pairingcode',
            options={'verbose_name': 'Pairing kod', 'verbose_name_plural': 'Pairing kodlar'},
        ),
        migrations.AlterModelOptions(
            name='sim',
            options={'verbose_name': 'SIM karta', 'verbose_name_plural': 'SIM kartalar'},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name': 'Webhook', 'verbose_name_plural': 'Webhooklar'},
        ),
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'verbose_name': 'Webhook yetkazish', 'verbose_name_plural': 'Webhook yetkazishlar'},
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='ownsms.device', verbose_name='Qurilma'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='ip_allowlist',
            field=models.JSONField(default=list, verbose_name='IP allowlist'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Test rejimi'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=64, unique=True, verbose_name='Kalit hash'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ishlatilgan'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(max_length=16, verbose_name='Prefiks'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(default=False, verbose_name='Bekor qilingan'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(default=list, verbose_name='Ruxsatlar'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=60, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.CharField(max_length=40, verbose_name='Bajaruvchi'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target',
            field=models.CharField(blank=True, max_length=120, verbose_name='Obyekt'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='callback_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Callback URL'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ownsms.device', verbose_name='Qurilma'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yuboruvchi raqam'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='queued',
            field=models.BooleanField(default=True, verbose_name="Navbatga qo'yilgan"),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rotate_sims',
            field=models.BooleanField(default=False, verbose_name='SIM almashtirish'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yuborish vaqti'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='ownsms.sim', verbose_name='SIM karta'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='running', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='text',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Jami'),
        ),
        migrations.AlterField(
            model_name='device',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ilova versiyasi'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(max_length=64, unique=True, verbose_name='Qurilma tokeni'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi ko'rinish"),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='message',
            name='callback_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Callback URL'),
        ),
        migrations.AlterField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ownsms.campaign', verbose_name='Rassilka'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan'),
        ),
        migrations.AlterField(
            model_name='message',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ownsms.device', verbose_name='Qurilma'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Jo'natilgan"),
        ),
        migrations.AlterField(
            model_name='message',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Xato kodi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Idempotency kaliti'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='message',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lease tugashi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='queued',
            field=models.BooleanField(default=False, verbose_name="Navbatga qo'yilgan"),
        ),
        migrations.AlterField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejalashtirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='message',
            name='segments',
            field=models.IntegerField(default=1, verbose_name='Segmentlar'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ownsms.sim', verbose_name='SIM karta'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(default='queued', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(max_length=20, verbose_name='Qabul qiluvchi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='TTL (soniya)'),
        ),
        migrations.AlterField(
            model_name='pairingcode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='pairingcode',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='pairingcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='pairingcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='pairingcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Ishlatilgan'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='daily_quota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kunlik kvota'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='ownsms.device', verbose_name='Qurilma'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Standart'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='jitter_max',
            field=models.IntegerField(default=5, verbose_name='Tanaffus max (soniya)'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='jitter_min',
            field=models.IntegerField(default=2, verbose_name='Tanaffus min (soniya)'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Raqam'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.CharField(blank=True, max_length=40, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_per_day',
            field=models.IntegerField(default=500, verbose_name='Kunda'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_per_hour',
            field=models.IntegerField(default=200, verbose_name='Soatda'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_per_min',
            field=models.IntegerField(default=15, verbose_name='Daqiqada'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='subscription_id',
            field=models.IntegerField(verbose_name='Subscription ID'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='work_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish oxiri'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='work_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish boshi'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Yoqilgan'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='events',
            field=models.JSONField(default=list, verbose_name='Hodisalar'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(max_length=64, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='ownsms.account', verbose_name='Akkaunt'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Urinishlar'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='event',
            field=models.CharField(max_length=40, verbose_name='Hodisa'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='event_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Hodisa ID'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ownsms.message', verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Keyingi urinish'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='payload',
            field=models.JSONField(verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL'),
        ),
    ]
