# Generated by Django 5.2.15 on 2026-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownsms', '0009_alter_account_options_alter_apikey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Idempotency kaliti'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['device', 'status'], name='msg_device_status'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'lease_expires_at'], name='msg_status_lease'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='whd_status_retry'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('account', 'idempotency_key'), name='uniq_campaign_idempotency'),
        ),
    ]
